---
- name: Ensure old versions of Docker are not installed.
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-engine

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "{{ docker_yum_repo_url }}"
    dest: "/etc/yum.repos.d/docker-{{ docker_edition }}.repo"
    owner: root
    group: root
    mode: 0644

- name: Define the Docker package name.
  set_fact:
    docker_package_name: "{{ docker_package }}-{{ docker_version }}"
  when: docker_version != ''

- name: Install Docker.
  yum:
    name: "{{ docker_package_name | default(docker_package) }}"
    state: "{{ docker_package_state }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2

- name: Add insecure registry to systemd unit file.
  replace:
    path: /usr/lib/systemd/system/docker.service
    regexp: '^ExecStart=/usr/bin/dockerd$'
    replace: 'ExecStart=/usr/bin/dockerd --insecure-registry {{ docker_insecure_registry }}'

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: started
    enabled: True
    daemon_reload: yes
